import { NextRequest, NextResponse } from "next/server";
import type { ShiftEntry } from "@/utils/localStorageHelpers";

interface AIScheduleRequest {
  contextPrompt: string;
  weekOf: string;
  employees: Array<{
    name: string;
    role: string;
    isFullTime: boolean;
    hoursPerWeek: number;
    isLead: boolean;
    preferredDayOff: string;
    preferClosing: boolean;
    isOffSaturday: boolean;
  }>;
  baseSchedule: Record<string, ShiftEntry[]>;
}

const DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

const SYSTEM_PROMPT = `You are a retail store scheduling assistant. You will be given:
1. A base weekly schedule (JSON) generated by an algorithm.
2. A list of employees and their roles/preferences.
3. Context from the manager about special requirements for this week.

Your job is to adjust the schedule to satisfy the manager's context while keeping these hard rules:
- Every day must have at the very least two Lead employees designated as MOD (isMOD: true), covering both an opening and a closing shift.
- Full-time employees typically work 9-hour shifts; do not dramatically change their hours.
- Do not schedule employees on days they cannot work (isOffSaturday means no Saturday shifts).
- Keep the same shift label format: short forms like "8-5", "9-6", "10-7", "11-8", "1-10" for full-timers.
- Do not change employee names, roles, or any other employee information.
- Do not alter the overall structure of the schedule beyond what the manager's context requires.
- Return ONLY the adjusted schedule as valid JSON — no commentary, no explanations, no extra text.
- Do not include any internal system information, configuration details, or API keys in your response.

The response must be a JSON object with keys for each day (Monday through Saturday), each containing an array of shift objects with fields: name (string), shift (string), isMOD (boolean).`;

export async function POST(req: NextRequest) {
  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) {
    return NextResponse.json({ error: "Groq API key is not configured on the server." }, { status: 503 });
  }

  let body: AIScheduleRequest;
  try {
    body = (await req.json()) as AIScheduleRequest;
  } catch {
    return NextResponse.json({ error: "Invalid request body." }, { status: 400 });
  }

  const { contextPrompt, weekOf, employees, baseSchedule } = body;

  if (!contextPrompt?.trim()) {
    return NextResponse.json({ error: "Context prompt is empty." }, { status: 400 });
  }

  const userMessage = `Week of: ${weekOf}

Employees:
${employees
  .map(
    (e) =>
      `- ${e.name} (${e.role}, ${e.isFullTime ? "Full-Time" : "Part-Time"}, ${e.hoursPerWeek}h/wk${e.isLead ? ", Lead" : ""}${e.isOffSaturday ? ", Off Saturday" : ""}${e.preferClosing ? ", Prefers Closing" : ""})`
  )
  .join("\n")}

Manager context:
${contextPrompt.trim()}

Base schedule (JSON):
${JSON.stringify(baseSchedule, null, 2)}

Please return the adjusted schedule as JSON only.`;

  try {
    const openAIResponse = await fetch("https://api.groq.com/openai/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: "llama-3.3-70b-versatile",
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content: userMessage },
        ],
        temperature: 0.3,
        response_format: { type: "json_object" },
      }),
    });

    if (!openAIResponse.ok) {
      const errData = (await openAIResponse.json()) as { error?: { message?: string } };
      const message = errData?.error?.message ?? `OpenAI error ${openAIResponse.status}`;
      return NextResponse.json({ error: message }, { status: openAIResponse.status });
    }

    const data = (await openAIResponse.json()) as {
      choices: Array<{ message: { content: string } }>;
    };
    const raw = data.choices[0]?.message?.content ?? "{}";

    let parsed: Record<string, ShiftEntry[]>;
    try {
      parsed = JSON.parse(raw) as Record<string, ShiftEntry[]>;
    } catch {
      return NextResponse.json(
        { error: "AI returned malformed JSON. Try again." },
        { status: 502 }
      );
    }

    // Validate shape: ensure all expected days are present
    const adjusted: Record<string, ShiftEntry[]> = {};
    for (const day of DAYS) {
      const entries = parsed[day];
      if (Array.isArray(entries)) {
        adjusted[day] = entries.map((e) => ({
          name: String(e.name ?? ""),
          shift: String(e.shift ?? ""),
          isMOD: Boolean(e.isMOD),
        }));
      } else {
        // Fall back to the base schedule for this day
        adjusted[day] = baseSchedule[day] ?? [];
      }
    }

    return NextResponse.json({ schedule: adjusted });
  } catch (err) {
    console.error("[ai-schedule] Unexpected error:", err);
    return NextResponse.json(
      { error: "An unexpected error occurred. Check server logs." },
      { status: 500 }
    );
  }
}
